[package]
name = "hyli_tools"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "block_dbg"
path = "src/bin/block_dbg.rs"
required-features = ["ui"]

[[bin]]
name = "smt_auto_prover"
path = "src/bin/smt_auto_prover.rs"

[dependencies]
hyle-contract-sdk = { workspace = true }
client-sdk = { workspace = true, features = ["rest"] }
hyle-modules = { workspace = true }
smt-token = { workspace = true, features = ["client"] }

anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
config = { version = "0.15.9", default-features = false, features = ["toml"] }
serde = "1.0.219"
tracing = "0.1.41"
tokio = "1.45.1"
tracing-subscriber = "0.3.19"

# needs to match workspace
opentelemetry = { version = "0.28" }

# Feature UI
ratatui = { version = "0.29.0", features = ["crossterm"], optional = true }
crossterm = { version = "0.29.0", optional = true }
borsh = "1.5.7"
serde_json = "1.0.140"
google-cloud-storage = "0.24.0"

[features]
default = ["ui"]
ui = ["dep:ratatui", "dep:crossterm"]

[package.metadata.cargo-machete]
ignored = ["client-sdk", "opentelemetry"]
